<?php

/**
 * @file
 * Contains dbcountpatients.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function dbcountpatients_theme($existing, $type, $theme, $path) {
  return array(
    'dbcountpatients' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_help().
 */
function dbcountpatients_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dbcountpatients module.
    case 'help.page.dbcountpatients':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a Custom Fetcher for Dashboard Count Patients By Table.') . '</p>';
      return $output;

    default:
  }
}
