<?php

/**
 * @file
 * Contains dbpatientspertable.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function dbpatientspertable_theme($existing, $type, $theme, $path) {
  return array(
    'dbpatientspertable' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_help().
 */
function dbpatientspertable_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dbpatientspertable module.
    case 'help.page.dbpatientspertable':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a Custom Fetcher for Dashboard Patients Per Table By Site.') . '</p>';
      return $output;

    default:
  }
}
