<?php

use \Firebase\JWT\JWT;

/**
 * @file
 * Contains dbtests.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Site\Settings;

function dbtests_theme($existing, $type, $theme, $path) {
  return array(
    'dbtests' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_help().
 */
function dbtests_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dbTests module.
    case 'help.page.dbtests':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides D3 rendering of Test Viruses.') . '</p>';
      return $output;

    default:
  }
}

/**
 * @param $variables
 */
function dbtests_preprocess_page(&$variables) {
  $key = "LRV7B8rFVNhf24DgWOXk3nitL8WIY8mVIsrEQKhbBU/OSnoe5RdBoITDXo9u66QxxWiPD8+HJAF6p+ZiT46F1A==";
  $payload = array(
      "iss" => "https://coviddash.westat.com",
      "iat" => time(),
      "nbf" => time(),
      "exp" => time() + (24*60*60),
      "username" => "jtoomer@westat.com",
      "role" => "Admin"
  );
 
  $jwt = JWT::encode($payload, $key);

  // pass JWT variable to Drupal.Settings
  $variables['#attached']['drupalSettings']['dbtests']['jwt'] = $jwt;

  // pass URL Base variable to Drupal.Settings
  $variables['#attached']['drupalSettings']['dbtests']['api_url_base'] = Settings::get('api_url_base', 'https://api.vision-covid.org');
}